apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogginapp-deployment
spec:
  selector:
    matchLabels:
      app: blogginapp
  replicas: 2
  template:
    metadata:
      labels:
        app: blogginapp
    spec:
      containers:
        - name: blogginapp
          image: titsaa/blogginapp:latest # Updated image to private DockerHub image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred # Reference to the Docker registry secret
---
apiVersion: v1
kind: Service
metadata:
  name: blogginapp-ssvc
spec:
  selector:
    app: blogginapp
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: LoadBalancer
